server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Venky@1234
    url: jdbc:mysql://localhost:3306/assignment
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

